#!/bin/bash
set -e

# Setting the password
sed -i -e "s/root_password_sha2 =$/root_password_sha2 = $(echo -n $GRAYLOG_PASSWORD | sha256sum | awk '{print $1}')/" /etc/graylog/server/server.conf

# Wait for mongodb
while ! echo exit | nc -z -w 3 localhost 27017; do sleep 3; done

# Wait for mongodb
while ! echo exit | nc -z -w 3 localhost 9200;  do sleep 3; done

# Configure input
echo "Configuring UDP input"
mongo < /tmp/mongo-configuration.js || /bin/true

# Start it
echo "Starting graylog..."
cd /opt/graylog
#exec /sbin/setuser graylog /usr/bin/java -jar /opt/graylog/graylog.jar >> /var/log/graylog.log
exec /sbin/setuser graylog /usr/bin/java -jar /opt/graylog/graylog.jar server
