#!/bin/bash
set -e
# Create the data directory if it doesn't exist
mkdir -p /data/elasticsearch
chmod -R 775 /data
chown elasticsearch:elasticsearch /data/elasticsearch

mkdir -p /opt/elasticsearch/logs
chmod 775 /opt/elasticsearch/logs
chown elasticsearch:elasticsearch /opt/elasticsearch/logs

echo "Starting elasticsearch..."
cd /opt/elasticsearch
exec /sbin/setuser elasticsearch /opt/elasticsearch/bin/elasticsearch \
    -Des.path.data=/data/elasticsearch -Des.cluster.name=graylog2 >> /var/log/elasticsearch.log