#!/bin/bash
set -e

# Wait for server
while ! echo exit | nc -z -w 3 localhost 12900;  do sleep 3; done

# Start it
echo "Starting graylog-web-interface..."
cd /opt/graylog-web-interface
exec /sbin/setuser graylog /opt/graylog-web-interface/bin/graylog-web-interface >> /var/log/graylog-web-interface.log
